export const AUTOCOMPLETE_REQUEST = "AUTOCOMPLETE_REQUEST";
export const AUTOCOMPLETE_SUCCESS = "AUTOCOMPLETE_SUCCESS";
export const AUTOCOMPLETE_FAILED = "AUTOCOMPLETE_FAILED";

export const GET_CURRENT_WEATHER_REQUEST = "GET_CURRENT_WEATHER_REQUEST";
export const GET_CURRENT_WEATHER_SUCCESS = "GET_CURRENT_WEATHER_SUCCESS";
export const GET_CURRENT_WEATHER_FAILED = "GET_CURRENT_WEATHER_FAILED";


export const GET_FIVE_DAYS_OF_DAILY_REQUEST = "GET_FIVE_DAYS_OF_DAILY_REQUEST";
export const GET_FIVE_DAYS_OF_DAILY_SUCCESS = "GET_FIVE_DAYS_OF_DAILY_SUCCESS";
export const GET_FIVE_DAYS_OF_DAILY_FAILED = "GET_FIVE_DAYS_OF_DAILY_FAILED";


export const ADD_TO_FAVORITES = "SET_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FAVORITE";

export const CHANGE_TEMPERATURE_UNIT = "CHANGE_TEMPERATURE_UNIT";

export const GET_GEOLOCATION_SEARCH_FAILED = "GET_GEOLOCATION_SEARCH_FAILED";